# Generated by Django 5.2.6 on 2025-10-02 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Credoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='fichier_pdf',
            field=models.FileField(blank=True, null=True, upload_to='articles/pdfs/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='contenu',
            field=models.TextField(blank=True),
        ),
    ]
