# Generated by Django 5.2.6 on 2026-01-10 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Credoapp', '0002_article_fichier_pdf_alter_article_contenu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intervenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('titre', models.CharField(help_text='Ex: Expert Marketing, CEO de ...', max_length=200)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='intervenants/')),
                ('bio', models.TextField(blank=True, help_text='Courte biographie')),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='webinaire',
            name='background_image',
            field=models.ImageField(blank=True, help_text='Image de fond pour le header', null=True, upload_to='webinaires/backgrounds/'),
        ),
        migrations.AddField(
            model_name='webinaire',
            name='duree',
            field=models.CharField(default='1h', help_text='Ex: 1h 30m', max_length=50),
        ),
        migrations.AddField(
            model_name='webinaire',
            name='etat',
            field=models.CharField(choices=[('a_venir', 'À venir'), ('en_direct', 'En direct'), ('replay', 'Replay disponible'), ('termine', 'Terminé')], default='a_venir', max_length=20),
        ),
        migrations.AddField(
            model_name='webinaire',
            name='slug',
            field=models.SlugField(blank=True, help_text='Généré automatiquement si vide', max_length=250, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='webinaire',
            name='image',
            field=models.ImageField(blank=True, help_text='Affiche', null=True, upload_to='webinaires/'),
        ),
        migrations.AddField(
            model_name='webinaire',
            name='intervenants',
            field=models.ManyToManyField(blank=True, related_name='webinaires', to='Credoapp.intervenant'),
        ),
    ]
