# Generated by Django 5.2.6 on 2026-01-12 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Credoapp', '0003_intervenant_webinaire_background_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AxeIntervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Ex: Marketing, Communication, Orientation', max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=120, null=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('message_cle', models.CharField(blank=True, help_text="Ex: 'Ne choisis pas ta carrière au hasard'", max_length=255)),
                ('icone', models.CharField(blank=True, help_text="Nom de l'icône FontAwesome ou emoji", max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TypeFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Ex: Formation Continue, Alternance, Hybride', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='formation',
            name='description',
        ),
        migrations.AddField(
            model_name='formation',
            name='avantages',
            field=models.TextField(blank=True, help_text='Pourquoi nous ? (Avant/Après)'),
        ),
        migrations.AddField(
            model_name='formation',
            name='brochure_pdf',
            field=models.FileField(blank=True, null=True, upload_to='formations/brochures/'),
        ),
        migrations.AddField(
            model_name='formation',
            name='description_courte',
            field=models.TextField(default=1, help_text='Accroche pour la liste'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formation',
            name='duree',
            field=models.CharField(blank=True, help_text='Ex: 3 jours / 20 heures', max_length=100),
        ),
        migrations.AddField(
            model_name='formation',
            name='lieu',
            field=models.CharField(blank=True, help_text='Présentiel / En ligne', max_length=255),
        ),
        migrations.AddField(
            model_name='formation',
            name='objectifs_cles',
            field=models.TextField(blank=True, help_text='Ce que vous allez gagner'),
        ),
        migrations.AddField(
            model_name='formation',
            name='pour_qui',
            field=models.TextField(blank=True, help_text='Cibles : Bacheliers, Commerçants...'),
        ),
        migrations.AddField(
            model_name='formation',
            name='programme_detaille',
            field=models.TextField(blank=True, help_text='Liste des modules'),
        ),
        migrations.AddField(
            model_name='formation',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='formation',
            name='axe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formations', to='Credoapp.axeintervention'),
        ),
        migrations.AddField(
            model_name='formation',
            name='type_formation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Credoapp.typeformation'),
        ),
    ]
