# Generated by Django 5.2.6 on 2026-01-13 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Credoapp', '0005_inscriptionformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinaire',
            name='ressource_pdf',
            field=models.FileField(blank=True, help_text='Document (PDF) à partager avec les participants', null=True, upload_to='webinaires/ressources/'),
        ),
    ]
